services:
  openbao-server:
    image: bao-server
    container_name: bao_server
    mem_swappiness: 0 
    networks: 
      - secured-network
    command: ["server", "-dev", '-dev-root-token-id="dev-only-token"']
  openbao-client:
    image: bao-client
    container_name: bao_client
    networks: 
      - secured-network


networks:
  secured-network: {}
